import numpy as np
from numpy import random 
#rand() for creating random float numbers of given range
x=random.rand(100)
print("Random floats generated by rand() = ",x)
#rand for only one number
y=random.rand()
print("Single float by rand() = ",y)
print()
#randint() for creating random integers within given range
z=random.randint(100) #generates a random number within 100
print("Random integer generated by randint() = ",z)
#randint with size specification
a=random.randint(100,size=5) #generates 1D array of random numbers within 100
b=random.randint(100,size=(3,5)) #generates 2D array of random numbers within 100
print("Random 1D array generated by randint() = ",a)
print("Random 2D array generated by randint() = ",b)
print()

#Choice() choose within given range of values or given values
arr=np.array([1,2,3,])
c=random.choice(arr)
print("Chosen within arr = ",c) #chooses one element from arr
print()
#choice with size specification
d=random.choice(arr,size=5) #generates 1D array of elements in arr
e=random.choice(arr,size=(3,5))  #generates 2D array of elements in arr
#choice() repeats same elements to create array from given arr if size is larger than no of elements in given arr
print("Random 1D array created by choice() from given arr = ",d)
print("Random 2D array created by choice() from given arr = ",e)